import React from 'react';
import styled from 'styled-components';

const StyledMain = styled.div`
`

const MainDiv = () => {
  return (
    <StyledMain>
      <main>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Neque volutpat ac tincidunt vitae semper quis lectus. Scelerisque eu ultrices vitae auctor eu augue ut lectus arcu. Feugiat vivamus at augue eget arcu dictum varius duis. Sapien pellentesque habitant morbi tristique senectus et. Lectus mauris ultrices eros in cursus turpis. Enim diam vulputate ut pharetra sit amet. Auctor urna nunc id cursus. Rhoncus aenean vel elit scelerisque mauris pellentesque. Pharetra diam sit amet nisl suscipit. Tortor vitae purus faucibus ornare suspendisse sed nisi. Duis ut diam quam nulla porttitor massa id neque aliquam. Congue mauris rhoncus aenean vel elit. Lacus viverra vitae congue eu consequat ac felis. Ipsum nunc aliquet bibendum enim facilisis gravida neque. At augue eget arcu dictum varius duis at consectetur lorem. Eu tincidunt tortor aliquam nulla facilisi cras fermentum odio. Augue eget arcu dictum varius duis. Suscipit tellus mauris a diam.

        Purus in massa tempor nec feugiat nisl pretium. Dis parturient montes nascetur ridiculus. Ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae. Scelerisque varius morbi enim nunc. Eu lobortis elementum nibh tellus molestie nunc non. Congue mauris rhoncus aenean vel elit scelerisque. Non pulvinar neque laoreet suspendisse interdum consectetur libero. Volutpat consequat mauris nunc congue nisi. Fringilla est ullamcorper eget nulla. Feugiat pretium nibh ipsum consequat nisl vel. Pellentesque massa placerat duis ultricies. Risus at ultrices mi tempus imperdiet nulla. Penatibus et magnis dis parturient montes nascetur ridiculus mus mauris. Est velit egestas dui id ornare. In aliquam sem fringilla ut morbi tincidunt augue interdum velit. Nunc mattis enim ut tellus elementum sagittis vitae. Dui nunc mattis enim ut tellus elementum sagittis vitae. Fringilla ut morbi tincidunt augue interdum velit euismod. Sollicitudin aliquam ultrices sagittis orci.

        At in tellus integer feugiat scelerisque varius morbi enim. Nullam non nisi est sit amet facilisis magna etiam tempor. Nulla pellentesque dignissim enim sit amet venenatis. Tempor id eu nisl nunc mi ipsum faucibus vitae aliquet. Magna sit amet purus gravida quis blandit turpis. Cursus sit amet dictum sit amet justo donec. Nulla porttitor massa id neque aliquam vestibulum morbi blandit cursus. Lacinia quis vel eros donec ac odio. Ut sem viverra aliquet eget sit amet tellus cras. Volutpat sed cras ornare arcu dui vivamus arcu felis. Quis imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Ac tortor vitae purus faucibus ornare suspendisse. Dui vivamus arcu felis bibendum ut tristique et egestas. Magna fermentum iaculis eu non diam phasellus vestibulum lorem sed. Non sodales neque sodales ut etiam sit. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Blandit massa enim nec dui nunc mattis enim ut tellus. A cras semper auctor neque vitae tempus. Ut venenatis tellus in metus vulputate eu scelerisque felis.

        Sit amet cursus sit amet dictum sit amet justo donec. Quam elementum pulvinar etiam non quam lacus. Tincidunt arcu non sodales neque sodales. Dignissim cras tincidunt lobortis feugiat vivamus at augue. Congue quisque egestas diam in arcu cursus euismod. Netus et malesuada fames ac turpis egestas integer eget aliquet. Porttitor leo a diam sollicitudin tempor. Laoreet id donec ultrices tincidunt arcu non sodales neque. Nam aliquam sem et tortor consequat id porta. Sed sed risus pretium quam vulputate. Orci eu lobortis elementum nibh tellus molestie. Ac felis donec et odio pellentesque diam volutpat commodo. Montes nascetur ridiculus mus mauris. Arcu cursus euismod quis viverra. Vitae congue mauris rhoncus aenean vel elit scelerisque. Diam quam nulla porttitor massa id neque aliquam. Ut etiam sit amet nisl. Auctor neque vitae tempus quam pellentesque nec nam aliquam. Consequat ac felis donec et.

        Pulvinar neque laoreet suspendisse interdum. Libero justo laoreet sit amet cursus sit amet dictum sit. Felis imperdiet proin fermentum leo vel orci porta. Elementum tempus egestas sed sed. Tortor at auctor urna nunc. Pharetra massa massa ultricies mi quis hendrerit dolor. Aliquam ut porttitor leo a diam sollicitudin tempor id. Imperdiet massa tincidunt nunc pulvinar sapien. Ornare quam viverra orci sagittis eu volutpat odio. Arcu cursus vitae congue mauris rhoncus aenean. Suspendisse in est ante in nibh mauris. Lacus laoreet non curabitur gravida arcu ac tortor dignissim. Diam maecenas sed enim ut sem. Eros donec ac odio tempor orci dapibus ultrices in iaculis. Neque egestas congue quisque egestas diam in arcu cursus. Amet porttitor eget dolor morbi non arcu risus quis. Vel pharetra vel turpis nunc eget lorem dolor. Netus et malesuada fames ac turpis egestas integer eget aliquet. In hac habitasse platea dictumst quisque sagittis.

        Nec dui nunc mattis enim ut. Nulla facilisi etiam dignissim diam. Varius sit amet mattis vulputate enim nulla. Mi in nulla posuere sollicitudin aliquam ultrices sagittis. Viverra nibh cras pulvinar mattis. Quam vulputate dignissim suspendisse in est ante in. Aliquam etiam erat velit scelerisque. Ipsum dolor sit amet consectetur adipiscing elit ut. Diam vel quam elementum pulvinar. Vel turpis nunc eget lorem dolor sed viverra ipsum. Morbi blandit cursus risus at ultrices.

        Quam elementum pulvinar etiam non quam lacus suspendisse. Lobortis mattis aliquam faucibus purus in massa tempor nec. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies. Et sollicitudin ac orci phasellus egestas tellus rutrum. Sit amet luctus venenatis lectus. Auctor elit sed vulputate mi. Pellentesque sit amet porttitor eget. Risus quis varius quam quisque id diam vel quam. Quam vulputate dignissim suspendisse in est ante in nibh. Sed velit dignissim sodales ut eu. Tellus integer feugiat scelerisque varius morbi. Ut tellus elementum sagittis vitae et leo duis. Nisl condimentum id venenatis a condimentum vitae sapien pellentesque habitant. Vel facilisis volutpat est velit. Tortor vitae purus faucibus ornare suspendisse sed nisi lacus. Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi. Fringilla ut morbi tincidunt augue interdum velit euismod in pellentesque.

        Nisi est sit amet facilisis magna etiam tempor orci. Ultricies tristique nulla aliquet enim tortor at. Sed velit dignissim sodales ut eu sem integer vitae justo. Bibendum neque egestas congue quisque. Orci eu lobortis elementum nibh. Id neque aliquam vestibulum morbi blandit cursus. Ullamcorper sit amet risus nullam. Malesuada fames ac turpis egestas integer eget aliquet nibh. Vitae et leo duis ut diam quam nulla porttitor massa. Odio aenean sed adipiscing diam. Venenatis tellus in metus vulputate eu scelerisque. Purus in massa tempor nec feugiat nisl pretium. Sapien eget mi proin sed libero enim sed faucibus turpis. Posuere lorem ipsum dolor sit amet consectetur. Feugiat scelerisque varius morbi enim nunc faucibus a pellentesque sit. Senectus et netus et malesuada fames ac turpis. Enim ut sem viverra aliquet. Est sit amet facilisis magna etiam tempor orci eu. In hac habitasse platea dictumst.

        Ipsum nunc aliquet bibendum enim. Sollicitudin tempor id eu nisl nunc mi ipsum. Pellentesque sit amet porttitor eget dolor morbi non arcu risus. Imperdiet proin fermentum leo vel orci porta non. Sit amet porttitor eget dolor morbi non arcu risus. Donec massa sapien faucibus et. Viverra adipiscing at in tellus integer feugiat scelerisque. Porttitor massa id neque aliquam vestibulum morbi. Sit amet aliquam id diam maecenas ultricies mi eget. Enim praesent elementum facilisis leo. Ornare massa eget egestas purus viverra. Lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque. Aliquet nibh praesent tristique magna sit amet. Gravida cum sociis natoque penatibus et. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras. Malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. Justo eget magna fermentum iaculis eu non. Fermentum dui faucibus in ornare quam viverra orci sagittis eu. Egestas congue quisque egestas diam in arcu cursus. Eu ultrices vitae auctor eu augue ut lectus arcu bibendum.

        Congue quisque egestas diam in arcu. Urna cursus eget nunc scelerisque. Dignissim enim sit amet venenatis urna cursus eget nunc. Id diam maecenas ultricies mi eget mauris. Facilisis gravida neque convallis a cras semper auctor neque. Egestas sed tempus urna et pharetra pharetra massa massa ultricies. Est placerat in egestas erat imperdiet sed euismod nisi porta. Aenean et tortor at risus viverra adipiscing at. Sit amet volutpat consequat mauris nunc congue nisi. In pellentesque massa placerat duis ultricies lacus. Ac ut consequat semper viverra nam libero justo laoreet sit. Viverra ipsum nunc aliquet bibendum enim facilisis gravida. Nulla facilisi etiam dignissim diam.

        Potenti nullam ac tortor vitae. Sapien pellentesque habitant morbi tristique senectus. Non tellus orci ac auctor augue mauris augue neque gravida. At in tellus integer feugiat scelerisque varius morbi enim nunc. Dignissim convallis aenean et tortor at risus. Elit duis tristique sollicitudin nibh sit amet. Gravida cum sociis natoque penatibus et magnis dis parturient. Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Maecenas sed enim ut sem viverra aliquet eget sit. Tortor at risus viverra adipiscing at in tellus integer feugiat. Nulla facilisi cras fermentum odio. Id volutpat lacus laoreet non curabitur gravida. Habitasse platea dictumst vestibulum rhoncus. Nam aliquam sem et tortor consequat id porta. Malesuada proin libero nunc consequat. Tristique et egestas quis ipsum suspendisse ultrices gravida. Massa sed elementum tempus egestas. Lacus sed viverra tellus in.

        Tortor condimentum lacinia quis vel eros donec. Suspendisse ultrices gravida dictum fusce ut placerat orci nulla. Sagittis aliquam malesuada bibendum arcu vitae. Cursus in hac habitasse platea dictumst. Scelerisque felis imperdiet proin fermentum leo. Orci phasellus egestas tellus rutrum tellus. Malesuada fames ac turpis egestas sed tempus urna et pharetra. Ac tortor vitae purus faucibus ornare suspendisse. Ornare arcu dui vivamus arcu felis bibendum. Sit amet porttitor eget dolor morbi non arcu risus. Id diam vel quam elementum pulvinar etiam non quam lacus. Volutpat maecenas volutpat blandit aliquam etiam. Magna sit amet purus gravida quis blandit. Eget dolor morbi non arcu risus quis varius quam quisque. Mattis pellentesque id nibh tortor id aliquet. Pharetra vel turpis nunc eget lorem dolor sed. Dolor morbi non arcu risus quis. Dictum sit amet justo donec enim diam vulputate ut pharetra. Dolor magna eget est lorem ipsum dolor sit. Faucibus in ornare quam viverra orci sagittis.

        Et molestie ac feugiat sed lectus vestibulum mattis. Purus sit amet luctus venenatis. Vitae suscipit tellus mauris a diam. Odio morbi quis commodo odio. Eget arcu dictum varius duis at. Cras adipiscing enim eu turpis egestas. Nisl rhoncus mattis rhoncus urna neque. Ut morbi tincidunt augue interdum velit euismod in pellentesque. Ac tincidunt vitae semper quis lectus nulla. Vel orci porta non pulvinar neque. Pellentesque id nibh tortor id aliquet. Sed risus ultricies tristique nulla aliquet.

        Dui accumsan sit amet nulla facilisi morbi. Enim facilisis gravida neque convallis a. Lectus sit amet est placerat in egestas erat imperdiet sed. Pharetra et ultrices neque ornare aenean euismod elementum nisi. Nec ultrices dui sapien eget mi proin sed. Molestie ac feugiat sed lectus. Euismod lacinia at quis risus sed vulputate odio. Tempus iaculis urna id volutpat lacus. Augue lacus viverra vitae congue eu consequat. Elit pellentesque habitant morbi tristique senectus et netus. Ipsum a arcu cursus vitae congue mauris rhoncus. Malesuada proin libero nunc consequat interdum varius sit. Velit sed ullamcorper morbi tincidunt ornare massa.

        Nulla malesuada pellentesque elit eget gravida. Sit amet facilisis magna etiam tempor orci eu lobortis elementum. Convallis a cras semper auctor neque vitae tempus quam pellentesque. Pellentesque elit eget gravida cum. Ipsum dolor sit amet consectetur adipiscing. Leo in vitae turpis massa sed elementum tempus egestas. Pellentesque elit eget gravida cum sociis natoque. Eu turpis egestas pretium aenean pharetra magna ac placerat vestibulum. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Ornare arcu odio ut sem nulla pharetra diam. Ut placerat orci nulla pellentesque dignissim. Netus et malesuada fames ac turpis egestas. Feugiat sed lectus vestibulum mattis ullamcorper.

        Amet consectetur adipiscing elit duis tristique sollicitudin nibh. Natoque penatibus et magnis dis parturient montes nascetur ridiculus. Id eu nisl nunc mi ipsum faucibus vitae aliquet nec. Semper auctor neque vitae tempus quam pellentesque nec nam aliquam. Non curabitur gravida arcu ac tortor dignissim convallis aenean et. Netus et malesuada fames ac turpis egestas. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Dui accumsan sit amet nulla facilisi morbi tempus. Laoreet id donec ultrices tincidunt arcu non sodales neque. Neque vitae tempus quam pellentesque nec. Commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Turpis tincidunt id aliquet risus feugiat in ante. Dignissim enim sit amet venenatis.

        Libero volutpat sed cras ornare arcu dui. Fermentum dui faucibus in ornare quam. Sit amet massa vitae tortor condimentum lacinia quis. Habitant morbi tristique senectus et netus et malesuada. Est placerat in egestas erat imperdiet sed euismod nisi porta. Sed faucibus turpis in eu mi bibendum neque egestas congue. Urna porttitor rhoncus dolor purus non. Neque laoreet suspendisse interdum consectetur. Dignissim convallis aenean et tortor at risus viverra adipiscing. Cras tincidunt lobortis feugiat vivamus at augue eget arcu. Eget sit amet tellus cras adipiscing enim eu turpis egestas. Leo duis ut diam quam nulla porttitor. Faucibus pulvinar elementum integer enim neque volutpat ac.

        Phasellus faucibus scelerisque eleifend donec pretium vulputate. Id diam maecenas ultricies mi eget mauris pharetra. Morbi tincidunt augue interdum velit euismod in pellentesque massa placerat. Sit amet est placerat in. Dictum non consectetur a erat. Morbi tristique senectus et netus et malesuada fames ac. Amet consectetur adipiscing elit pellentesque habitant morbi. Iaculis eu non diam phasellus vestibulum lorem. Consequat semper viverra nam libero justo laoreet sit. Suspendisse interdum consectetur libero id. Morbi tincidunt augue interdum velit euismod. Quis blandit turpis cursus in hac. Ac turpis egestas integer eget aliquet nibh praesent tristique magna. Sed risus pretium quam vulputate dignissim suspendisse in est. Erat velit scelerisque in dictum non. Aliquet sagittis id consectetur purus ut faucibus pulvinar. Aliquet bibendum enim facilisis gravida neque convallis. Placerat vestibulum lectus mauris ultrices eros in cursus. Mi tempus imperdiet nulla malesuada pellentesque elit eget. Risus nec feugiat in fermentum posuere.
      </main>
    </StyledMain>
  )
};

export default MainDiv;
